name: Tests

on: push

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, pcntl, bcmath
        coverage: none
    - name: Install PHPUnit
      run: |
        wget -O phpunit https://phar.phpunit.de/phpunit-8.phar
        chmod +x phpunit
    - name: PHPUnit
      run: ./phpunit tests/*
